### ISSUE TITLE
Make library logger agnostic

### ISSUE THREAD

**Issue by spetrunin** [jensneuse/graphql-go-tools#150]
Possible solutions:
- provide generic logger interface
- Implement wrappers around popular logger engines

**Comment by jensneuse** [comment]
Have you thought about performance implications in hit paths? Should the generic logger be part of this library or should this be another library? I've seen libraries trying to solve the problem. E.g.: https://github.com/src-d/go-log
However I'm still not convinced how to solve the problem. Should this be a very lightweight low level wrapper without any allocations where the user of the graphql go tools library needs to implement an interface or use one of the defaults? What's the common sense of implementing logging in a library?

**Comment by spetrunin** [comment]
The main goal here is to be able to integrate library into project with any logger
