### ISSUE TITLE
Make handlers embeddable

### ISSUE THREAD

**Issue by spetrunin** [jensneuse/graphql-go-tools#151]
With the current implementation, the library could not be integrated into an existing application as it uses std http muxer and should be started separately

One of possible solutions - provide generic handlers which will be possible to integrate into any routing library compatible with std handler interface

**Comment by jensneuse** [comment]
Makes sense, will work on it.

**Comment by jensneuse** [comment]
I've investigated this a bit more.
It looks like I'm not using a mux anywhere in this library, see:
https://github.com/jensneuse/graphql-go-tools/blob/6405fd5905b4ac87d5d26cbe16c6d4a01f395c2c/pkg/http/handler.go#L12

The only place where I use a mux is in the graphql gateway repo which only tries to showcase possibilities. Did I overlook anything?

**Comment by spetrunin** [comment]
What about playground?
```
mux := http.NewServeMux()

	playgroundURLPrefix := "/playground"
	playgroundURL := ""
	err = playground.ConfigureHandlers(mux, playground.Config{
		URLPrefix:                   playgroundURLPrefix,
		PlaygroundURL:               playgroundURL,
		GraphqlEndpoint:             graphqlEndpoint,
		GraphQLSubscriptionEndpoint: graphqlEndpoint,
	})
```

**Comment by jensneuse** [comment]
You're right, I'm using it in the playground package. Will fix this.
