### ISSUE TITLE
[Critical] Make possible to convert json map into objects array

### ISSUE THREAD

**Issue by spetrunin** [jensneuse/graphql-go-tools#152]
https://stackoverflow.com/questions/56705157/best-way-to-define-a-map-object-in-graphql-schema

**Comment by jensneuse** [comment]
Could you go a bit more into detail what you'd like to achieve? A use case would be helpful to understand this issue. I've investigated the link but don't think I fully understand the problem you'd like to solve.

**Comment by spetrunin** [comment]
@jensneuse 
for example, we have next JSON
```
{
    "rights": {
        "429d3b1b3bd146e95563f2ed71851b75": {
            "someProperty": "a",
        }
    }
}
```

We could not map it directly to GraphQL type and need to trasform it into something like this:
```
{
	"rights": [{
		"key": "429d3b1b3bd146e95563f2ed71851b75",
		"value": {
			"someProperty": "a"
		}
	}]
}
```

which we could map into such schema
```
type Value { someProperty: String }
type Rights { key: String value: Value }
type RightsHolder { rights: [Rights ] }
```
