### ISSUE TITLE
Provide minimal example for federation

### ISSUE THREAD

**Issue by asp24** [jensneuse/graphql-go-tools#230]
There is a branch with federation support merged into planner refactoring branch. Could you please describe current federation support state or provide minimal example how to start with federation?

**Comment by jensneuse** [comment]
https://github.com/jensneuse/graphql-go-tools/blob/c1ec2edc5c96fadac406247f5474247f38774b85/pkg/engine/datasource/graphql_datasource/graphql_datasource_test.go#L998

Take the config above to configure the engine for the below federation example.

https://github.com/99designs/gqlgen/tree/master/example/federation

To understand how to configure the engine have a look at these tests:

https://github.com/jensneuse/graphql-go-tools/blob/c1ec2edc5c96fadac406247f5474247f38774b85/pkg/engine/resolve/resolve_test.go#L1055

If all is configured correctly federation works as expected including subscriptions, defer and stream.

**Comment by asp24** [comment]
Thnx for advice. 
From the source code it's unclear how datasources configuration must be generated.
For the first source, type User declared in this source, but configured in the `ChildNodes` section

```golang
plan.DataSourceConfiguration{
{
    RootNodes: []plan.TypeField{
        {
            TypeName:   "Query",
            FieldNames: []string{"me"},
        },
    },
    ChildNodes: []plan.TypeField{
        {
            TypeName:   "User",
            FieldNames: []string{"id", "username"},
        },
    },
    Custom: ConfigJson(Configuration{
        Fetch: FetchConfiguration{
            URL: "http://user.service",
        },
        Federation: FederationConfiguration{
            Enabled:    true,
            ServiceSDL: "extend type Query {me: User} type User @key(fields: \"id\"){ id: ID! username: String!}",
        },
    }),
    Factory: federationFactory,
}
```

For the second source declared type `Product` defined in `RootNodes` and `ChildNodes` sections. Subscription is also defined, but does not exists in the `ServiceSDL` string
```golang
{
    RootNodes: []plan.TypeField{
        {
            TypeName:   "Query",
            FieldNames: []string{"topProducts"},
        },
        {
            TypeName:   "Subscription",
            FieldNames: []string{"updatedPrice"},
        },
        {
            TypeName:   "Product",
            FieldNames: []string{"upc", "name", "price"},
        },
    },
    ChildNodes: []plan.TypeField{
        {
            TypeName:   "Product",
            FieldNames: []string{"upc", "name", "price"},
        },
    },
    Custom: ConfigJson(Configuration{
        Fetch: FetchConfiguration{
            URL: "http://product.service",
        },
        Subscription: SubscriptionConfiguration{
            URL: "ws://product.service",
        },
        Federation: FederationConfiguration{
            Enabled:    true,
            ServiceSDL: "extend type Query {topProducts(first: Int = 5): [Product]} type Product @key(fields: \"upc\") {upc: String! name: String! price: Int!}",
        },
    }),
    Factory: federationFactory,
}
```

Is there a set of rules how this configuration could be generated from gql schemas?

**Comment by jensneuse** [comment]
I'm currently building a tool which introspects multiple federated services and automatically configures everything for you. I'll keep you posted once done.

**Comment by chedom** [comment]
@jensneuse  [example](https://github.com/jensneuse/graphql-go-tools/tree/master/examples/federation) have been added.
I think you can close the issue.
