### ISSUE TITLE
Parsing scalar types in query arguments

### ISSUE THREAD

**Issue by sosedoff** [jensneuse/graphql-go-tools#248]
Not sure if i'm doing something wrong, here's an example error im getting when passing string arguments to a query that expects a scalar:

```graphql
scalar PublicKey

type Account {
  publicKey: PublicKey!
}

type query {
  account(
    publicKey: PublicKey!
  ): Account
}
```

Query:

```graphql
query MyQuery {
  account(publicKey: "example") {
    # omitted
  }
}
```

Returns an error: 

```json
{
  "errors": [
    {
      "message": "value: \"example\" doesn't satisfy inputType: PublicKey!",
      "path": [
        "query",
        "account"
      ],
      "locations": null
    }
  ]
}
```

But it works when passing the value as a variable:

```graphql
query MyQuery($key: PublicKey) {
  account(publicKey: $key) {
    # omitted
  }
}
```

Execution handle in Go:

```go
cfg := datasource.PlannerConfiguration{
	TypeFieldConfigurations: []datasource.TypeFieldConfiguration{
		{
			TypeName:  "query",
			FieldName: "__schema",
			DataSource: datasource.SourceConfig{
				Name:   "SchemaDataSource",
				Config: toJSON(datasource.SchemaDataSourcePlannerConfig{}),
			},
		},
	},
}

// schema is a []byte of the example schema provided in the issue
base, err := datasource.NewBaseDataSourcePlanner(schema, cfg, abstractlogger.NoopLogger)
if err != nil {
	return nil, err
}

err = base.RegisterDataSourcePlannerFactory("SchemaDataSource", datasource.SchemaDataSourcePlannerFactoryFactory{})
if err != nil {
	return nil, err
}

return execution.NewHandler(base, nil), nil
```

Does that mean passing the strings where the scalar is expected not possible, or am i missing configuration somewhere?

**Comment by jensneuse** [comment]
I'd suggest you to use the v2 engine.

If you don't want to use the low level tools, the graphql package is a convenient layer on top to make it easy to use.

https://github.com/jensneuse/graphql-go-tools/blob/d312d407000dd634350058c00078f49582701a5c/pkg/graphql/execution_engine_v2.go#L178

https://github.com/jensneuse/graphql-go-tools/blob/master/pkg/graphql/execution_engine_v2_test.go

If you want to use lower level with more flexibility:

https://github.com/jensneuse/graphql-go-tools/tree/master/pkg/engine

Packages plan + resolve is what you're looking for.
Both have lots of tests which should help you understand more.

Let me know if you have additional questions.

**Comment by sosedoff** [comment]
I should have clarified what i'm trying to do here first: i'm using this package to validate an incoming graphql request against a schema file, and if the request passes the check it's forwarded to the upstream graphql endpoint for actual execution - basically i'm implementing a filtering proxy.

Does that change any of your recommendations?

**Comment by sosedoff** [comment]
Figured it out, thanks for the pointer!
