### ISSUE TITLE
gateway pass header to each grapql service

### ISSUE THREAD

**Issue by SirReiva** [jensneuse/graphql-go-tools#270]
I`m testing gateway example and I don´t know how pass header recived by gateway to each service.

There are some documentation about that?

**Comment by jensneuse** [comment]
The config you generate should look similar to this:

https://github.com/jensneuse/graphql-go-tools/blob/e69d4234c60ecb812ef0ac4d608a49621843aa23/pkg/engine/datasource/graphql_datasource/graphql_datasource_test.go#L217

**Comment by jensneuse** [comment]
Please reopen in case you have additional questions.

**Comment by fouad1998** [comment]
Hi, I have took a look on different issue posted here in Github [#115](https://github.com/jensneuse/graphql-go-tools/issues/115) [#128](https://github.com/jensneuse/graphql-go-tools/pull/128) [#270](https://github.com/jensneuse/graphql-go-tools/issues/270) about passing request headers to new request made by the engine (Client - Gateway -> Gateway - Service) but I couldn't find out how, I have tried for example the following
```go
	if err = g.engine.Execute(r.Context(), &gqlRequest, &resultWriter, graphql.WithAdditionalHttpHeaders(r.Header)); err != nil {
		g.log.Error("engine.Execute", log.Error(err))
		w.WriteHeader(http.StatusInternalServerError)
		return
	}
```

but each time I fail the other service doesn't have access to the request headers. Can you please send us an example of code shows how to pass those headers or blog or even adding above your [example](https://github.com/jensneuse/graphql-go-tools/tree/e69d4234c60ecb812ef0ac4d608a49621843aa23/examples/federation)

thanks in advance

**Comment by cauchy2384** [comment]
Stuck with the same issue. Can't understand how to pass headers using WithAdditionalHttpHeaders.
Any good example?

thanks

**Comment by IsabelFreitas-catapult** [comment]
How do you this with subscriptions?
