### ISSUE TITLE
GraphQLDataSource wrongfully requires the presence of data in response from datasource

### ISSUE THREAD

**Issue by bcgodev** [jensneuse/graphql-go-tools#274]
https://github.com/jensneuse/graphql-go-tools/blob/90831cf28164c840329d1c6cb1620855cff3ad11/pkg/execution/datasource/datasource_graphql.go#L463

`datasource_graphql.go` requires the presence of `data` in response, or it will raise an error with `"Key path not found"`.

However, it the [GraphQL June2018 Spec](https://spec.graphql.org/June2018/#sec-Data) states that `If an error was encountered before execution begins, the data entry should not be present in the result.`.

Expected: When `GraphQLDataSource` receives a response with `errors` without `data`, the GraphQLDataSource.Resolve does not raise error and pass the errors to the clients.

**Comment by jensneuse** [comment]
You're looking at the legacy "engine".
Have a look at the new version, the error should be fixed there:
https://github.com/jensneuse/graphql-go-tools/blob/90831cf28164c840329d1c6cb1620855cff3ad11/pkg/engine/datasource/graphql_datasource/graphql_datasource.go#L877

If you discover that the new engine is affected by the same problem, please report back.
If you'd like to fix the old engine you can raise a PR, from my side, it's unmaintained and just for compatibility reasons still in the repo.

**Comment by bcgodev** [comment]
Thanks for the quick explanation. Appreciate it 😄
