### ISSUE TITLE
Can I define custom directive for handler or engine?

### ISSUE THREAD

**Issue by bcgodev** [jensneuse/graphql-go-tools#282]
Hi, I am using `graphql-go-tools` as a gateway to proxy query to an internal service and proxy mutation to another service. It goes well so far.

I found some custom directives in the examples, like `@key`, `@provides`, `directive @user`, `directive @hasRole` and `@GraphQLDataSource`, but I can't find the implementation.

My goal is to use directive to implement authorization validation like `directive @hasRole` to validate the token and the query input.

Is it possible to do it with directive or is there a better way to do it?

Here's my code if it helps.

```golang
	schemaString := "xxxx"
	upstreamURL := "https://bcgodev/api/graphql"
	schema, err := graphql.NewSchemaFromString(schemaString)
	if err != nil {
		ogrus.Panic(err)
	}
	validation, err = mutationSchema.Validate()
	if err != nil {
		logrus.Panic(err)
	}
	if !validation.Valid {
		validation.Errors.ErrorByIndex(0)
		logrus.Panic("mutation schema is not valid:", validation.Errors.Error(), "first one is:", validation.Errors.ErrorByIndex(0))
	}
defaultClient := httpclient.DefaultNetHttpClient

	factory := graphfederation.NewEngineConfigV2Factory(
		&http.Client{
			Transport: &http.Transport{
				MaxIdleConns:    10,
				IdleConnTimeout: 30 * time.Second,
			},
			CheckRedirect: defaultClient.CheckRedirect,
			Jar:           defaultClient.Jar,
			Timeout:       defaultClient.Timeout,
		},
		graphql_datasource.Configuration{
			Fetch: graphql_datasource.FetchConfiguration{
				URL: upstreamURL,
			},
			Federation: graphql_datasource.FederationConfiguration{
				Enabled:    true,
				ServiceSDL: string(schema.Document()),
			},
		},
	)conf, err := factory.EngineV2Configuration()
	if err != nil {
		logrus.Panic(err)
	}

	executionEngine, _ := graphql.NewExecutionEngineV2(context.TODO(), abstractlogger.NewLogrusLogger(logrus.New(), log.DebugLevel), conf)
	mergedSchema, err := factory.MergedSchema()
	if err != nil {
		logrus.Panic(err)
	}
	ghHandler := http2.NewGraphqlHTTPHandler(mergedSchema, executionEngine, nil, logger)

	gin.SetMode(gin.DebugMode)
	engine := gin.Default()

	engine.POST("/graphql", gin.WrapH(ghHandler))
```

**Comment by jensneuse** [comment]
There's nothing out of the box available. This library is tool low level for such things.

That said, I can imagine how it's possible.
Attach a custom directive to some field definitions.
Write a middleware that extracts a role from the HTTP context.
Parse, normalize and validate a query.
Then use the astvisitor.Walker to walk through the Operation and collect all fields and types.
Once collected, compare with the schema if a role was needed for the fields.

You could obviously raise a PR with a solution to solve the problem in a generic way.
Could be a nice addition as a new higher level package.

**Comment by chedom** [comment]
@bcgodev  sorry for the delay.
Check this #284 PR pls.
I have added [`hasRole`](https://github.com/chedom/graphql-go-tools/tree/feature/add-operation-middleware/examples/federation/gateway/authorization) directive to the `federation` example.
If you have any questions, please ping me.

**Comment by bcgodev** [comment]
@chedom Thanks!! Appreciate your helm. I'll check #284.
