### ISSUE TITLE
Question : Ratelimiting based on query complexity for federation

### ISSUE THREAD

**Issue by saravind-hotstar** [jensneuse/graphql-go-tools#302]
We would like to know if go-tools supports rate limiting for federation by taking following aspects 
Depth limiting - Depth of calls to backend graphql services
Vanilla Rate limiting - Restrict number of query, mutations, subscriptions
Query complexity based limiting - Based on complexity of query stop federating queries 

Can go-tools be extended to support this features

**Comment by jensneuse** [comment]
There's already a package to address the problem of determining the complexity of a GraphQL Operation.
https://github.com/jensneuse/graphql-go-tools/blob/master/pkg/middleware/operation_complexity/operation_complexity.go

Other than that, the library is very much low level so you can build a rate limiter on top of it, of course.

**Comment by jensneuse** [comment]
close due to inactivity
