### ISSUE TITLE
Question: response header forwarding

### ISSUE THREAD

**Issue by dnerdy** [jensneuse/graphql-go-tools#309]
Hi @jensneuse! @StevenACoffman reached out to you at some point and asked about header forwarding. He noted that you said "We can already forward headers. It's just not easy to find." Does this include response header forwarding? I see the WithAdditionalHttpHeaders execution option for setting data source request headers. I'm not immediately seeing a way to access data source responses (other than via a custom http transport / RoundTripper on the federation http client and stashing some info on the request context).

**Comment by jensneuse** [comment]
If you set the header on the Request, it can be used in input templates using this syntax:
`{{ .request.headers.Authorization }}`

set header:
https://github.com/jensneuse/graphql-go-tools/blob/71ca10e362dbf4f94c6c7a6f20027ecd0ab3a3da/pkg/graphql/request.go#L67

headers planner:
https://github.com/jensneuse/graphql-go-tools/blob/71ca10e362dbf4f94c6c7a6f20027ecd0ab3a3da/pkg/engine/plan/plan.go#L782

Returning Headers from an upstream to the client is not supported.
Could you elaborate on the use case?

**Comment by dnerdy** [comment]
> Returning Headers from an upstream to the client is not supported.

Thanks for confirming.

We have mutations that set cookies (and a few other headers) that need to be forwarded back to the client.

**Comment by dnerdy** [comment]
> Returning Headers from an upstream to the client is not supported.

This is what we ended up doing. We stashed header forwarding state on the context and used a custom HTTP client to do the forwarding. The code looks something like this:

```
////////// Engine configuration...
engineConfigFactory := graphql.NewFederationEngineConfigFactory(
    datasources,
    graphql.WithFederationHttpClient(NewHTTPClientWithHeaderForwardingTransport()),
)

////////// Custom HTTP client transport...
func (t *httpHeaderForwardingTransport) RoundTrip(req *http.Request) (*http.Response, error) {
    headerForwarding := getHeaderForwarding(req.Context())  // Get header forwarding state set with WithHeaderForwarding
    headerForwarding.ForwardRequestHeaders(req)

    resp, err := t.wrappedTransport.RoundTrip(req)
    if err != nil {
        return nil, err
    }

    headerForwarding.CopyResponseHeaders(resp)
    return resp, nil
}

////////// In the handler for our GraphQL endpoint...
headerForwarding := NewHTTPHeaderForwarder(r)
ctx = WithHeaderForwarding(ctx, headerForwarding)

// ...get engine, execute request...

headerForwarding.ForwardResponseHeaders(w)
```

This would be a bit simpler if engine.Execute had hooks that exposed the raw upstream requests and responses.
