### ISSUE TITLE
the request AST should be merged before invoking middlewares

### ISSUE THREAD

**Issue by jensneuse** [jensneuse/graphql-go-tools#31]
Nested inline fragments and fragment spreads should be resolved/merged before invoking the first middleware. This should simplify the middleware development because middlewares don't need to traverse complex nested structures but only work on a "clean" graph.

**Comment by flexzuu** [comment]
A uniform way to access the arguments of a field. That does handle default arguments, literal arguments and variables as arguments would be helpful too. This could be done in the same step by inlining defaults & variables.

**Comment by jensneuse** [comment]
Implemented in the next branch.
