### ISSUE TITLE
Entity queries do not include variables used in directives

### ISSUE THREAD

**Issue by dnerdy** [jensneuse/graphql-go-tools#316]
When a variable, for example `$someSkipCondition`, is used as the argument to a directive like so:
```
query MyReviews($someSkipCondition: Boolean!) {
    me {           // users service
        reviews {  // reviews service
            body
            notes @skip(if: $someSkipCondition)
        }
    }
}
```
the entity query sent to the reviews service doesn't include the `$someSkipCondition` variable.

The query that's sent is:
```
{"query":"query($representations: [_Any!]!){_entities(representations: $representations){... on User {reviews {body notes @skip(if: $someSkipCondition)}}}}","variables":{"representations":[{"id":$$0$$,"__typename":"User"}]}}
```

This is the query that's expected:
```
{"query":"query($representations: [_Any!]!, $someSkipCondition: Boolean!){_entities(representations: $representations){... on User {reviews {body notes @skip(if: $someSkipCondition)}}}}","variables":{"someSkipCondition":$$1$$,"representations":[{"id":$$0$$,"__typename":"User"}]}}
```

Note that the query that's sent isn't valid since it references a variable that doesn't exist.

Khan/graphql-go-tools#1 has a test that demonstrates this issue.

**Comment by jensneuse** [comment]
That's easy to fix. I'll check that test. Btw. I'm currently on your last PR.
