### ISSUE TITLE
Skipped fields are set to null

### ISSUE THREAD

**Issue by dnerdy** [jensneuse/graphql-go-tools#320]
When a selection includes a field with a `@skip` or `@include` directive, graphql-go-tools correctly forwards this directive to the upstream service (this is also what Apollo does). If the skip condition is true, the upstream service omits the field from the response. graphql-go-tools adds the field back and sets the value to `null`, however. graphql-go-tools should instead omit such fields.

Here's an example that can be run in the examples/federation playground:
```
query($skip:Boolean!){
  me {
    username
    reviews @skip(if:$skip) {
      author {
        username
      }
      body
      product {
        name 
      }
    }
  }
}
```
When $skip is true, this returns:
```
{
  "data": {
    "me": {
      "username": "Me",
      "reviews": null
    }
  }
}
```
The expected result is instead:
```
{
  "data": {
    "me": {
      "username": "Me",
    }
  }
}
```
Note that if the selection set only includes "reviews" (and not "username"), the GraphQL spec isn't clear about what to return. In this case Apollo returns:
```
{
  "data": {
    "me": {}
  }
}
```

This issue is especially problematic when the skipped field is a non-null field. This is because the null bubbles up to the nearest nullable parent field, meaning all the other selection data is lost. (Also note that graphql-go-tools doesn't appear to add a resolve error in this case. I'll file another issue for that.)

**Comment by jensneuse** [comment]
Are you going to tackle this?

**Comment by chedom** [comment]
Hi @dnerdy,
I faced the same issue. 
I thought the gateway could evaluate the `skip`/`include` condition when normalizing an incoming request. In this case, the gateway does not request the skipped fields in upstream service at all. Here is my [solution](https://github.com/chedom/graphql-go-tools/commit/f2363a0cce8ca0b6f5df830fc44c246da220bff7#diff-08b552115bea0c7f95978f7e5181a74e6b4281aa17243d04724549f9733bfbf2) with tests.

Is it required to proxy directives ? Are there any cases when the condition cannot be evaluated on the gateway ?

**Comment by jensneuse** [comment]
> Hi @dnerdy, I faced the same issue. I thought the gateway could evaluate the `skip`/`include` condition when normalizing an incoming request. In this case, the gateway does not request the skipped fields in upstream service at all. Here is my [solution](https://github.com/chedom/graphql-go-tools/commit/f2363a0cce8ca0b6f5df830fc44c246da220bff7#diff-08b552115bea0c7f95978f7e5181a74e6b4281aa17243d04724549f9733bfbf2) with tests.
> 
> Is it required to proxy directives ? Are there any cases when the condition cannot be evaluated on the gateway ?

I think the skip or include evaluation should happen during execution, not in normalisation. The problem with your approach I see is that I cannot "compile" and cache an execution plan. Once normalised, skip depends on the variables. However, skip should depend on the variables during execution, not normalisation. Otherwise it's not possible to re-use normalized cached plans. So I suggest that we evaluate the variables at runtime in order to skip or include s field.

**Comment by dnerdy** [comment]
@jensneuse your assistance with this would be appreciated, if you have the time. Omitting fields based on upstream responses has proven to be a bit difficult (and as I mentioned before, it seems like this strategy might be incompatible with non-GraphQL data sources).

You mentioned having a renderer that conditionally renders the field in the input based on the skip/include condition and also having a corresponding flag on fields to indicate whether the field should be skipped in the response. This sounds like a reasonable plan to me. Please let me know if there's anything I can do to help move this forward.

**Comment by jensneuse** [comment]
done
