### ISSUE TITLE
Impelement federation of interface fields

### ISSUE THREAD

**Issue by dnerdy** [jensneuse/graphql-go-tools#328]
This is a big one. If a field has an interface type and the concrete types are federated, the query planner either ignores the field or generates an upstream operation that isn't valid.

There appear to be (at least) three areas that need to be updated:
- The EnterField method in the configuration visitor
- The GraphQL data source code that generates the representations variable
- The GraphQL data source code that adds fields to upstream operations

The EnterField method -- non-child interface fields are skipped during query planning. This is because interface types aren't listed in root nodes; entity queries must be on concrete types (and therefore interfaces can't be entry points). (Note that interface fields owned by the same service work fine because interfaces appear in the list of child nodes.) This will be tricky. See "Interfaces and root fields" below.

Representations -- `__typename` in the ["representations" variable in the upstream operation is static](https://github.com/jensneuse/graphql-go-tools/blob/47621af0e2831f40171c681f77777da2ead0eefa/pkg/engine/datasource/graphql_datasource/graphql_datasource.go#L540). `__typename` needs to instead be set to the type of the input object.

Upstream operation -- the inline fragment in an upstream operation is assumed to have [same type as the parent object](https://github.com/jensneuse/graphql-go-tools/blob/47621af0e2831f40171c681f77777da2ead0eefa/pkg/engine/datasource/graphql_datasource/graphql_datasource.go#L581) of the enclosing field. This isn't the case for interfaces! There needs to be a separate inline fragment for each concrete type that implements the interface. Note this also means that [when fields are added](https://github.com/jensneuse/graphql-go-tools/blob/47621af0e2831f40171c681f77777da2ead0eefa/pkg/engine/datasource/graphql_datasource/graphql_datasource.go#L1126) they need to be added to each of the inline fragments. Furthermore, if the selection in the original operation contains inline fragments, the fields in these fragments need to be added to the appropriate concrete inline fragments.

Interfaces and root fields:

Although this doesn't align exactly with the spec, let's make the assumption that the same field on all the concrete types that implement an interface are resolved by the same service. For example, if the "id" field of  `type Dog implements Pet` is resolved by the "pets" data source, then the "id" field of `type Cat implements Pet` is resolved by the "pets" data source as well. The federation spec is a bit vague about how federated interfaces work; it isn't clear how one would construct a set of schemas where the above wasn't true (where would the `@external` directive on the interface go?), so this solution seems good enough--or a least a good first step. It's certainly better than the current situation where federated interface fields don't work at all.

How would this work?

During planning (in the [configurationVisitor EnterField method](https://github.com/jensneuse/graphql-go-tools/blob/47621af0e2831f40171c681f77777da2ead0eefa/pkg/engine/plan/plan.go#L1400)), if typeName is an interface and a planner isn't found with a child node for the typeName, fieldName pair, look up the first concrete type for the interface and set typeName to that. Then, a planner will be constructed based on the service that owns the field of the concrete type.

**Comment by dnerdy** [comment]
https://github.com/jensneuse/graphql-go-tools/pull/334 implements federation of abstract fields by using the first concrete type of an interface for planning purposes. Assuming fields with the same name have the same ownership (for concrete types that implement an interface) seems like a reasonable restriction, but assuming field configurations for types are the same is problematic. For example, types may have different federation keys or and fields may have different `@requires` directives.

A schema normalization approach where selections from abstract types are removed from the schema seems like the most sound approach. It would also enable fixing https://github.com/jensneuse/graphql-go-tools/issues/335 in a reasonable way. That issue is currently very difficult to fix because it's hard to know if a required field is selected by some deeply nested inline fragment with an abstract type condition.

I'm going to abandon https://github.com/jensneuse/graphql-go-tools/pull/334. Some of the changes in that PR can be used for the new approach, but the core of the approach will be fundamentally different.

The high-level idea of the normalization approach is to remove all abstract type selections from the schema. That means replacing inline fragments with abstract type conditions with an equivalent set of fragments with concrete type conditions. It also means replacing selections like `{ pet {name}}` with `{pet {... on Cat {name} ... on Dog {name}}}`. Then the planner will only ever encounter concrete enclosing types.

The plan for the normalization approach is as follows:

1. Add the ability to copy nodes in the AST. This is needed for copying selection sets (and everything they contain).
2. Add a new normalization pass with the following normalization steps
    - Expand abstract inline fragments
    - Expand abstract selections to concrete inline fragment selections
    - Remove incompatible inline fragments
    - Note: this pass would pass would be placed between the fragment inlining and merging passes
3. Make it so a federation root is created the first time...
    - An inline fragment is processed
    - field is processed
    - Note: the "federation root" is the operation and entity query in the upstream operation
    - Note: currently a federation root is only created the first time a field is processed
    - Note: an inline fragment will still need to be added manually for concrete types
4. Make it so the `__typename` variable is dynamic the federation root corresponds an abstract type

For https://github.com/jensneuse/graphql-go-tools/issues/335: after the above normalization steps are combined with fragment merging, selection sets will only have one level of inline fragments, so tracking when to skip "added" required fields can be done on a per- (concrete) type basis.

**Comment by jensneuse** [comment]
I like the idea of "normalizing" the problem away. We do this a lot ourselves. E.g. fragment inlining, variable extraction, list value coercion.

**Comment by jensneuse** [comment]
One thing I'm thinking about: What happens if a union has 20 union members? Or 20 types implement an interface. What would you send to the upstream in this case? Also, wouldn't the upstream operation become quite bloated with concrete inline fragments?

**Comment by dnerdy** [comment]
> One thing I'm thinking about: What happens if a union has 20 union members? Or 20 types implement an interface. What would you send to the upstream in this case? Also, wouldn't the upstream operation become quite bloated with concrete inline fragments?

Unions already require explicit inline fragments, so they aren't a factor; the selection sets can be used as-is. Interfaces are another matter. Yes, the upstream operation could become bloated. For what it's worth, entity queries already require concrete inline fragments for each type (because the _Entity type is a union). The question is: will child selections be a problem? We could consider yet another normalization step for upstream operations where common interface fields are collapsed again below the top-level. I'm not sure how much of an issue the bloat will be in practice.
