### ISSUE TITLE
drop packr

### ISSUE THREAD

**Issue by tmc** [jensneuse/graphql-go-tools#359]
Can you drop packr and reduce the number of third party dependencies?

**Comment by jensneuse** [comment]
> Can you drop packr and reduce the number of third party dependencies?

What's the reason for the request? How about you opening a PR? 😊

**Comment by tmc** [comment]
> > Can you drop packr and reduce the number of third party dependencies?
> 
> What's the reason for the request? How about you opening a PR? 😊

Just wanting a little software on potentially internet-exposed software as possible. PR opened.

**Comment by jensneuse** [comment]
Thank you for your contribution! =)
