### ISSUE TITLE
Resolver first implementations?

### ISSUE THREAD

**Issue by parsnips** [jensneuse/graphql-go-tools#361]
Where's a good spot to look for a resolver first implementation? My project leverages [graphql-go/graphql](https://github.com/graphql-go/graphql) to dynamically create resolvers and types from different schema definition languages.  I've found some useful things in this project and was wondering if this could be a direct replacement.

Cheers!

**Comment by jensneuse** [comment]
@parsnips That's a very good question. Unfortunately, the answer is that as of now, the library doesn't support the user to "implement" resolvers. What this library does instead is to allow you to build a system that "dynamically" generates resolvers. You can describe an API that has various datasources, e.g. REST & GraphQL APIs, and just by looking at the Schema and the meta data (configuration), it's possible to generate a proxy that can talk to all your services as if they were a single GraphQL Schema. All this can be done at runtime, no compilation step required. If you're looking for a framework that actually lets you write resolvers, this library currently doesn't support that use case. It could be implemented, but it's not the focus so far. If you're interested, you could build a layer on top of graphql-go-tools to achieve similar functionality like e.g. gqlgen. I hope this helps. Please correct me if I misunderstood your question.

**Comment by parsnips** [comment]
@jensneuse thanks for your response! That directly confirms my intuition after studying the codebase for a few hours :)

> It could be implemented, but it's not the focus so far. If you're interested, you could build a layer on top of graphql-go-tools to achieve similar functionality like e.g. gqlgen. I hope this helps.

We may take a swing at this in the near future!
