### ISSUE TITLE
How can I pass the Headers sent to Gateway to specific service

### ISSUE THREAD

**Issue by marcosstefani** [jensneuse/graphql-go-tools#364]
https://github.com/jensneuse/graphql-go-tools/blob/b484a4fba0f8f72b6ffea6105db777c278b9e9a6/examples/federation/gateway/main.go#L50

I have one service, that need to bearer Authentication. I need to send to that call one header of authentication that was passed to gateway call. Can you help me?

**Comment by mxncson** [comment]
@marcosstefani did you find any solution ?

**Comment by cordjr** [comment]
You can use a custom RoundTripper on your HttpClient and propagate the
headers through the RoundTrip method.

José Cordeiro de Oliveira junior
Analista de Sistemas / Desenvolvedor



Em qua., 7 de jun. de 2023 às 07:00, PBholewasi ***@***.***>
escreveu:
