### ISSUE TITLE
DispatchRequest

### ISSUE THREAD

**Issue by flexzuu** [jensneuse/graphql-go-tools#65]
DispatchRequest needs to handle variables.
It currently only does handle have a field for query and operation name, not variables.

https://github.com/jensneuse/graphql-go-tools/blob/58e708802492050485a4133458f0125ff452a06a/pkg/proxy/http/proxy.go#L64-L66

**Comment by jensneuse** [comment]
Thanks for requesting this feature. It wasn't yet needed but is definitely a requirement to build a graphql proxy.

**Comment by jensneuse** [comment]
Api deprecated, will be handled in a standalone proxy repo.
