### ISSUE TITLE
ServeHTTP should handle DispatchRequest?

### ISSUE THREAD

**Issue by flexzuu** [jensneuse/graphql-go-tools#66]
The error is currently not returned neither logged so debugging when the backend URL is not reachable is hard.

https://github.com/jensneuse/graphql-go-tools/blob/58e708802492050485a4133458f0125ff452a06a/pkg/proxy/http/proxy.go#L123-L128

**Comment by jensneuse** [comment]
Seems like this error is indeed swallowed. This should be fixed!
