### ISSUE TITLE
HTTP Proxy should run middleware.OnResponse

### ISSUE THREAD

**Issue by flexzuu** [jensneuse/graphql-go-tools#67]
Currently, the HTTP middleware does not run the OnResponse to transform the result.

**Comment by jensneuse** [comment]
In the current implementation this wasn't yet required. That said it's easy to implement.

**Comment by mvid** [comment]
It's a bit trickier than that, currently. Right now the Invoker doesn't have the concept of rewriting responses. It only has `RewriteRequest` and `middlewaresOnRequest`. Calling `InvokeMiddlewares` only calls `middlewaresOnRequest`.

To add this feature, we would need to modify the Invoker abstraction.

**Comment by jensneuse** [comment]
API deprecated, will be moved into own repository.
