### ISSUE TITLE
Proxy does not support introspection

### ISSUE THREAD

**Issue by flexzuu** [jensneuse/graphql-go-tools#68]
This is because the introspection query fails validation.
```ValidationMiddleware: Invalid Request: RuleName: RequiredArguments, Description: TypeNotDefined```

**Comment by jensneuse** [comment]
I've created #70 to address this issue. Once error messages are useful we should look at this issue here. Also it's currently not possible to use the "extends" keyword which is addressed in #69 . Once both of these issues are implemented it should be easy to fix this issue.

**Comment by jensneuse** [comment]
Implemented in the next branch.
