### ISSUE TITLE
improve documentation

### ISSUE THREAD

**Issue by jensneuse** [jensneuse/graphql-go-tools#79]
This repo should improve documentation of its inner workings like parser, lexer, lookup, walker, , validation, printer. There should be both, inline explanations as well as external docs to explain how all the parts play together. Debugging should also be addressed as it's a bit unusual because of heavy use of references.

**Comment by jensneuse** [comment]
Should document k6 load testing too.

**Comment by StarpTech** [comment]
Is it done or prematurely closed? I'm looking for some docs about the internals.
